weights: yolov5s.pt
cfg: /home/marques/1_Delivery/Alerion/boston-dynamics-spot/IA/neuron/models/yolov5s.yaml
data: /home/marques/1_Delivery/Alerion/boston-dynamics-spot/IA/neuron/data/detect_data.yaml
hyp: /home/marques/1_Delivery/Alerion/boston-dynamics-spot/IA/neuron/data/hyps/hyp.scratch-high.yaml
epochs: 50
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 24
project: runs/train
name: handle_det_test
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/handle_det_test4
